### ISSUE TITLE
Company CRA Number not update

### ISSUE THREAD

**Issue by franklintrinh367** [franklintrinh367/mean_project#105]
![image](https://user-images.githubusercontent.com/12133982/54837364-903c7080-4c9c-11e9-81b1-3a34288f79d7.png)
All fields work fine except for that one. It doesnt update CRANumber

**Comment by Abdallahman-habyarimana** [comment]
Go there and merge the new pull. don't bring back this !!!

**Comment by franklintrinh367** [comment]
This has been opened for a long time, and if you already fixed it then close it.
That's why we have an issue here. No one brings back anything. Check the date of posting.
The purpose of issue section is to report bugs to peer so anyone can go and fix it.

**Comment by franklintrinh367** [comment]
As long as it's your module, you and renata can merge it. Just ask her to review your work. It's not like permission going through me. I explained it really carefully and over again.
