### ISSUE TITLE
login

### ISSUE THREAD

**Issue by 101096098** [franklintrinh367/mean_project#134]
I'm trying to log (admin) and receiving :Session time out, please log in!
Can you check please

**Comment by 101096098** [comment]
I can't access the admins page to work in the project

**Comment by franklintrinh367** [comment]
Do you still have that problem?

**Comment by 101096098** [comment]
Hi Frank. 
I ca access now. Thank you!

**Comment by 101096098** [comment]
Franck, can you, for now, put the admin time longer, it's login out too fast and need to log a lot

**Comment by franklintrinh367** [comment]
Sorry, that must be the inactivity feature which i set to 30s.
Ill fix that
