### ISSUE TITLE
Rocommandation

### ISSUE THREAD

**Issue by Abdallahman-habyarimana** [franklintrinh367/mean_project#45]
Hello, 

I changed something in the register in this part, I recommend you to do this for the candidate, admin, etc if possible, every user of the jc consult has it's own credentials.

              //Check if the user visited more than once
              if (token.visited > 1) {
                // check if the role is company
                if (token.role === 'Company') {
                  //assign to the company home page
                  window.location.assign('/company_details')
                } else {
                  this.closeDialog('')
                  window.location.assign('/home')
                }

**Comment by Abdallahman-habyarimana** [comment]
What I mean if the user logged in will be redirected to his/her homepages based on its role. I've seen that you did but when the user register.

**Comment by franklintrinh367** [comment]
Yeah, there was a bug and i forgot to fix that after the presentation.
Well, now i got what you were trying to say yesterday.
Yeah, thats fine

**Comment by franklintrinh367** [comment]
Initially, my intent was to only redirect user at first time login. But that is fine by me

**Comment by Abdallahman-habyarimana** [comment]
I understand your intentions and I hope everything still working. For this is when the user visited the web more than once ? Is all user have the same home page?

**Comment by franklintrinh367** [comment]
Well they should have the same homepage.
