### ISSUE TITLE
Job 

### ISSUE THREAD

**Issue by franklintrinh367** [franklintrinh367/mean_project#62]
[Object Object]

![image](https://user-images.githubusercontent.com/12133982/54459418-01c86c00-473d-11e9-8474-cb68c006e034.png)

I think when user click on the link, job descriptions will be displayed

![image](https://user-images.githubusercontent.com/12133982/54459577-6b487a80-473d-11e9-958d-2f9556c5f31d.png)

**Comment by Abdallahman-habyarimana** [comment]
Yeah instead of calling job description we can call it job title. This should be working by tomorrow
