### ISSUE TITLE
Token expired but user doesn't log out

### ISSUE THREAD

**Issue by franklintrinh367** [franklintrinh367/mean_project#78]
Description:
While user logged in and is using the page.
In the event token expired but user still is in the page, it won't log them out.
After that the behavior is abnormal so needed check

**Comment by tddag** [comment]
Solved!
Check if token is expired for pages which require token details, log user out and ask for Re-login

**Comment by franklintrinh367** [comment]
New issue:
+cannot go to profile after login.
Needed fix
Thanks man
